# Exported from Render on 2024-09-03T18:12:51Z
services:
- type: web
  name: vibe-share-app-project
  runtime: node
  repo: https://github.com/7FOX7/vibe-share-app-project
  plan: free
  envVars:
  - key: VITE_API_BASE_URL
    sync: false
  - key: BUCKET_NAME
    sync: false
  - key: KEY_FILE_NAME
    sync: false
  - key: PROJECT_ID
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_NAME
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_HOST
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: node index.js
  buildFilter:
    paths:
    - cd backend\index.js
    - cd frontend\main.jsx
  rootDir: backend
version: "1"
